# Minimal Powerlevel10k config based on ~/.local/share/chezmoi/dot_p10k.zsh.
# Run `p10k configure` in an interactive shell if you want to regenerate it.

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  vcs
  prompt_char
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  virtualenv
  kubecontext
  aws
  time
)

typeset -g POWERLEVEL9K_MODE=compatible
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''

typeset -g POWERLEVEL9K_DIR_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=255
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=178
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196

typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR=true
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=255
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

# Short kube prompt: last two cluster hyphen segments (e.g. prod-5) and
# kubeflow-* namespace prefix stripped (e.g. creator-code).
_p9k_kubecontext_short() {
  local cluster=${${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_CLUSTER:t}}:-${P9K_KUBECONTEXT_NAME:t}}
  local -a parts=(${(s:-:)cluster})
  if (( ${#parts} >= 3 )); then
    cluster="${parts[-2]}-${parts[-1]}"
  fi
  if [[ -n $P9K_KUBECONTEXT_NAMESPACE ]]; then
    print -rn -- "$cluster/${P9K_KUBECONTEXT_NAMESPACE#kubeflow-}"
  else
    print -rn -- "$cluster"
  fi
}
typeset -g POWERLEVEL9K_KUBECONTEXT_CONTENT_EXPANSION='$(_p9k_kubecontext_short)'
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION="$POWERLEVEL9K_KUBECONTEXT_CONTENT_EXPANSION"

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION='❮'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION='❮'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_FOREGROUND=255
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_FOREGROUND=196
typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true

typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
