# =============
# general
# =============

set -g mouse on
set -g set-titles on
set -g set-titles-string '#T'
set -g status on
setw -g automatic-rename on
setw -g automatic-rename-format '#T'
setw -g allow-rename on
set -g focus-events on

set -g monitor-bell on
set -g bell-action any
set -g visual-bell off

# vi keys in copy mode
set -g mode-keys vi

# windows/panes number from 1, renumber when closing
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# =============
# keybindings
# =============

bind | split-window -h
bind - split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind = select-layout tiled

# mouse wheel enters copy-mode
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" \
    "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

# =============
# copy mode (vi)
# =============

bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'C-v' send -X rectangle-toggle

# =============
# appearance
# =============

set -g status-interval 5
set -g status-left-length 40
set -g status-right-length 40

set -g @minimal-tmux-use-arrow false
set -g @minimal-tmux-bg '#95B179'
set -g @minimal-tmux-left-arrow ''
set -g @minimal-tmux-right-arrow ''

# =============
# plugins (TPM)
# =============

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'semi710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'roxma/vim-tmux-clipboard'

run '~/.tmux/plugins/tpm/tpm'
